watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 33
    padding:
      top: 7
      left: 7
      bottom: 0
      right: 7
    widgets:
      left: ["home", "media", "active_window"]
      center: ["clock"]
      right: ["weather", "volume", "power_menu"]

widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false

  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\HP\\Pictures\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 250
        image_per_page: 4
        show_buttons: true
        orientation: "portrait"
        image_spacing: 15
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 8
        enable_cache: true

  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#cba6f7"
      gradient_color_1: "#cba6f7"
      gradient_color_2: "#B4BEFE"
      bars_number: 8
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 1
      sleep_timer: 2
      hide_empty: false
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\HP\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\HP\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\HP\\Pictures" }
        - { title: "Videos", path: "C:\\Users\\HP\\Videos" }
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 50
        label_alt: 50
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "#cba6f7"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
      calendar:
        alignment: "center"
        offset_top: 6

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "6dff94a9a5cc4a59a2c30934260904"
      update_interval: 600
      hide_decimal: true
      location: "Taubate"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyDay: "\ue30a"
        snowyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"

      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        sleep: ["\udb82\udd04", "Sleep"]
        lock: ["\uf023", "Lock"]
        cancel: ["\udb81\udf3a", "Cancel"]

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 12
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: true